package order_4

import com.mycompany.app.bean.cal.Item

//https://blog.csdn.net/u010952582/article/details/92797141?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.compare&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.compare
//遍历orderId == 1的Item并累加其price并输出结果
rule "order_4"
salience 10
when

     $n:Number() from accumulate(

                $item1:Item( orderId == 1,$value:price),
                init(Integer i =0;Integer oI = 0;List inlist = new ArrayList();double total = 0;),
                action(
                       System.out.println("action println before:"+total);

                       total+=$value;

                      System.out.println("action println after:"+total);
                ),

                result(total)

    )

then
    System.out.println("then print:"+$n);

end
