server:
  port: 9060
spring:
  application:
    name: price-api

security:
  oauth2:
    client:
      client-id: priceService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.imooc.com:9090/oauth/token_key
