zuul:
  routes:
    api:
      url: http://gateway.imooc.com:9070
  sensitive-headers:
  host:
    maxTotalConnections: 10000
    maxPerRouteConnections: 10000
  semaphore:
    max-semaphores: 200
server:
  port: 8080
spring:
  application:
    name: admin-web
