pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {

    stage('Build') {
            steps {
                sh 'mvn -B -gs conf/settings.xml -DskipTests clean package'
            }
        }
    stage('checkstyle') {
                steps {
                    sh 'mvn checkstyle:checkstyle'
                }
            }

        stage('pmd') {
                    steps {
                        sh 'mvn pmd:pmd'
                    }
                    post {
                            always {
                             pmd(canRunOnFailed: true,pattern: '**/target/pmd.xml')
                              }
                            }
                }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

    }
}
