pipeline {
    agent {
        docker {
            image 'maven:4-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('pmd') {
                    steps {
                        sh 'mvn pmd:pmd'
                    }
                    post {
                            always {
                             pmd(canRunOnFailed: true,pattern: '**/target/pmd.xml')
                              }
                            }
                }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

    }
}
