server:
  port: 30002
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 112.74.31.211:8848
management:
  endpoints:
    web:
      exposure:
        incloud: '*'