
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  mode: LEGACYHTML5
  cache: false

jenkins:
  username: admin
  serverUrl:  http://47.105.193.166:8080
  password: zxcvbnm/8

logging:
  level:
    org.springframework: INFO
    com.mycompany: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

spring:
  application:
    name: app-name
server:
  port: 9090
